-- MySQL Script generated by MySQL Workbench
-- Tue Sep  9 18:02:34 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema git_scan_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `git_scan_db` ;
CREATE SCHEMA IF NOT EXISTS `git_scan_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `git_scan_db` ;

-- -----------------------------------------------------
-- Table `git_scan_db`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `git_scan_db`.`requests` ;

CREATE TABLE IF NOT EXISTS `git_scan_db`.`requests` (
  `idrequests` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL,
  `language` VARCHAR(45) NULL,
  `fork` TINYINT(1) NULL,
  `per_page` INT NULL,
  `sort` VARCHAR(45) NULL,
  `order` VARCHAR(45) NULL,
  `page_num` INT NULL,
  `query` VARCHAR(45) NULL,
  `total_count` VARCHAR(45) NULL,
  `incomplete_result` VARCHAR(45) NULL,
  PRIMARY KEY (`idrequests`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `git_scan_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `git_scan_db`.`users` ;

CREATE TABLE IF NOT EXISTS `git_scan_db`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `login` TEXT NULL,
  `id` INT NULL,
  `avatar_url` VARCHAR(2083) NULL,
  `url` VARCHAR(2083) NULL,
  `type` TEXT NULL,
  `site_admin` BINARY NULL,
  `html_url` VARCHAR(2083) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `login_UNIQUE` ON `git_scan_db`.`users` (`login` ASC);

CREATE UNIQUE INDEX `id_UNIQUE` ON `git_scan_db`.`users` (`id` ASC);


-- -----------------------------------------------------
-- Table `git_scan_db`.`repositories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `git_scan_db`.`repositories` ;

CREATE TABLE IF NOT EXISTS `git_scan_db`.`repositories` (
  `idrepositories` INT NOT NULL AUTO_INCREMENT,
  `id` INT NOT NULL,
  `name` TEXT NULL,
  `full_name` TEXT NULL,
  `description` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `pushed_at` DATETIME NULL,
  `language` TEXT NULL,
  `has_downloads` BINARY NULL,
  `has_wiki` BINARY NULL,
  `mirror_url` VARCHAR(2083) NULL,
  `default_branch` VARCHAR(45) NULL,
  `score` DECIMAL(5) NULL,
  `owner_id` INT NOT NULL,
  `homepage` VARCHAR(2083) NULL,
  `request_id` INT NOT NULL,
  `flag` TEXT NULL,
  `html_url` VARCHAR(2083) NULL,
  PRIMARY KEY (`idrepositories`, `id`, `owner_id`, `request_id`),
  CONSTRAINT `request`
    FOREIGN KEY (`request_id`)
    REFERENCES `git_scan_db`.`requests` (`idrequests`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `git_scan_db`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `git_id_UNIQUE` ON `git_scan_db`.`repositories` (`id` ASC);

CREATE UNIQUE INDEX `full_name_UNIQUE` ON `git_scan_db`.`repositories` (`full_name` ASC);

CREATE INDEX `request_idx` ON `git_scan_db`.`repositories` (`request_id` ASC);

CREATE INDEX `owner_idx` ON `git_scan_db`.`repositories` (`owner_id` ASC);


-- -----------------------------------------------------
-- Table `git_scan_db`.`repositories_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `git_scan_db`.`repositories_data` ;

CREATE TABLE IF NOT EXISTS `git_scan_db`.`repositories_data` (
  `idrepositories_data` INT NOT NULL AUTO_INCREMENT,
  `size` INT NULL,
  `stargazers_count` INT NULL,
  `watchers_count` INT NULL,
  `forks_count` INT NULL,
  `open_issues_count` INT NULL,
  `watchers` INT NULL,
  `has_issues` BINARY NULL,
  `forks` INT NULL,
  `open_issues` INT NULL,
  `repository_id` INT NULL,
  `timestamp` DATETIME NULL,
  PRIMARY KEY (`idrepositories_data`),
  CONSTRAINT `repository`
    FOREIGN KEY (`repository_id`)
    REFERENCES `git_scan_db`.`repositories` (`idrepositories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `repository_idx` ON `git_scan_db`.`repositories_data` (`repository_id` ASC);


-- -----------------------------------------------------
-- Table `git_scan_db`.`repositories_commits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `git_scan_db`.`repositories_commits` ;

CREATE TABLE IF NOT EXISTS `git_scan_db`.`repositories_commits` (
  `idrepositories_commits` INT NOT NULL AUTO_INCREMENT,
  `sha` TEXT NULL,
  `owner_id` INT NULL,
  `date` BLOB NULL,
  `additions` INT NULL,
  `deletions` INT NULL,
  `files_count` INT NULL,
  `repository_id` INT NULL,
  `html_url` VARCHAR(2083) NULL,
  PRIMARY KEY (`idrepositories_commits`),
  CONSTRAINT `repository`
    FOREIGN KEY (`repository_id`)
    REFERENCES `git_scan_db`.`repositories` (`idrepositories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `git_scan_db`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `repository_idx` ON `git_scan_db`.`repositories_commits` (`repository_id` ASC);

CREATE INDEX `owner_idx` ON `git_scan_db`.`repositories_commits` (`owner_id` ASC);

CREATE UNIQUE INDEX `sha_UNIQUE` ON `git_scan_db`.`repositories_commits` (`sha` ASC);


-- -----------------------------------------------------
-- Table `git_scan_db`.`repositories_issues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `git_scan_db`.`repositories_issues` ;

CREATE TABLE IF NOT EXISTS `git_scan_db`.`repositories_issues` (
  `idrepositories_issues` INT NOT NULL AUTO_INCREMENT,
  `repository_id` INT NULL,
  `owner_id` INT NULL,
  `number` INT NULL,
  `id` INT NULL,
  `title` TEXT NULL,
  `state` TEXT NULL,
  `locked` BINARY NULL,
  `created_at` DATETIME NULL,
  `closed_at` DATETIME NULL,
  `html_url` VARCHAR(2083) NULL,
  PRIMARY KEY (`idrepositories_issues`),
  CONSTRAINT `repository`
    FOREIGN KEY (`repository_id`)
    REFERENCES `git_scan_db`.`repositories` (`idrepositories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `git_scan_db`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `repository_idx` ON `git_scan_db`.`repositories_issues` (`repository_id` ASC);

CREATE INDEX `owner_idx` ON `git_scan_db`.`repositories_issues` (`owner_id` ASC);

CREATE UNIQUE INDEX `id_UNIQUE` ON `git_scan_db`.`repositories_issues` (`id` ASC);


-- -----------------------------------------------------
-- Table `git_scan_db`.`repositories_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `git_scan_db`.`repositories_comments` ;

CREATE TABLE IF NOT EXISTS `git_scan_db`.`repositories_comments` (
  `idrepositories_comments` INT NOT NULL AUTO_INCREMENT,
  `id` INT NULL,
  `owner_id` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `body` TEXT NULL,
  `type` TEXT NULL,
  `repository_id` INT NULL,
  PRIMARY KEY (`idrepositories_comments`),
  CONSTRAINT `repository`
    FOREIGN KEY (`repository_id`)
    REFERENCES `git_scan_db`.`repositories` (`idrepositories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `git_scan_db`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `owner_idx` ON `git_scan_db`.`repositories_comments` (`owner_id` ASC);

CREATE INDEX `repository_idx` ON `git_scan_db`.`repositories_comments` (`repository_id` ASC);

CREATE UNIQUE INDEX `id_UNIQUE` ON `git_scan_db`.`repositories_comments` (`id` ASC);


-- -----------------------------------------------------
-- Table `git_scan_db`.`users_network`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `git_scan_db`.`users_network` ;

CREATE TABLE IF NOT EXISTS `git_scan_db`.`users_network` (
  `idusers_network` INT NOT NULL AUTO_INCREMENT,
  `follower_id` INT NULL,
  `followed_id` INT NULL,
  PRIMARY KEY (`idusers_network`),
  CONSTRAINT `follower`
    FOREIGN KEY (`follower_id`)
    REFERENCES `git_scan_db`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `followed`
    FOREIGN KEY (`followed_id`)
    REFERENCES `git_scan_db`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `follower_idx` ON `git_scan_db`.`users_network` (`follower_id` ASC);

CREATE INDEX `followed_idx` ON `git_scan_db`.`users_network` (`followed_id` ASC);


-- -----------------------------------------------------
-- Table `git_scan_db`.`code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `git_scan_db`.`code` ;

CREATE TABLE IF NOT EXISTS `git_scan_db`.`code` (
  `idcode` INT NOT NULL AUTO_INCREMENT,
  `repository_id` INT NULL,
  `name` TEXT NULL,
  `url` VARCHAR(2083) NULL,
  `path` TEXT NULL,
  `sha` TEXT NULL,
  `html_url` VARCHAR(2083) NULL,
  `text_matches` BLOB NULL,
  PRIMARY KEY (`idcode`),
  CONSTRAINT `repository`
    FOREIGN KEY (`repository_id`)
    REFERENCES `git_scan_db`.`repositories` (`idrepositories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `repository_idx` ON `git_scan_db`.`code` (`repository_id` ASC);


-- -----------------------------------------------------
-- Table `git_scan_db`.`repositories_pulls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `git_scan_db`.`repositories_pulls` ;

CREATE TABLE IF NOT EXISTS `git_scan_db`.`repositories_pulls` (
  `idrepositories_pulls` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(2083) NULL,
  `id` INT NULL,
  `number` INT NULL,
  `state` TEXT NULL COMMENT '	',
  `locked` BINARY NULL,
  `title` TEXT NULL,
  `owner_id` INT NULL,
  `body` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `closed_at` DATETIME NULL,
  `merged_at` DATETIME NULL,
  `repository_id` INT NULL,
  `html_url` VARCHAR(2083) NULL,
  PRIMARY KEY (`idrepositories_pulls`),
  CONSTRAINT `repository`
    FOREIGN KEY (`repository_id`)
    REFERENCES `git_scan_db`.`repositories` (`idrepositories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `git_scan_db`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `repository_idx` ON `git_scan_db`.`repositories_pulls` (`repository_id` ASC);

CREATE INDEX `owner_idx` ON `git_scan_db`.`repositories_pulls` (`owner_id` ASC);

CREATE UNIQUE INDEX `id_UNIQUE` ON `git_scan_db`.`repositories_pulls` (`id` ASC);

SET SQL_MODE = '';
GRANT USAGE ON *.* TO mxia;
 DROP USER mxia;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'mxia' IDENTIFIED BY 'password';

GRANT ALL ON `git_scan_db`.* TO 'mxia';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
